// These settings trim package-manager noise and unnecessary metadata fetches.
APT::Install-Recommends "false";
Acquire::PDiffs "false";
Acquire::Languages "none";
Aptitude::Get-Root-Command "sudo:/usr/bin/sudo";
